FROM ckan/ckan-dev:2.11

USER root

# Instalar dependencias del sistema para spatial
RUN apt-get install -y python3-dev libxml2-dev libxslt1-dev libgeos-c1v5

# Instala supervisor, copia archivos de configuración y otorga permisos de escritura para el usuario ckan
RUN apt-get install -y supervisor && chown -R ckan:ckan-sys /var/log/supervisor
COPY supervisor/* /etc/supervisor/conf.d/

#Instala cron
RUN apt-get install -y cron

# Instala utilidades de desarrollo
RUN apt-get install -y nano procps curl

USER ckan

# Install any extensions needed by your CKAN instance
# - Make sure to add the plugins to CKAN__PLUGINS in the .env file
# - Also make sure all provide all extra configuration options, either by:
#   * Adding them to the .env file (check the ckanext-envvars syntax for env vars), or
#   * Adding extra configuration scripts to /docker-entrypoint.d folder) to update
#      the CKAN config file (ckan.ini) with the `ckan config-tool` command
#
# See README > Extending the base images for more details
#
# For instance:
#

### XLoader ###
#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-xloader.git@master#egg=ckanext-xloader' && \ 
#    pip3 install -r ${APP_DIR}/src/ckanext-xloader/requirements.txt && \
#    pip3 install -U requests[security]

### Spatial ###
RUN pip3 install -e 'git+https://github.com/ckan/ckanext-spatial.git@v2.3.1#egg=ckanext-spatial' && \
    pip3 install -r ${APP_DIR}/src/ckanext-spatial/requirements.txt

### Geoview ###
RUN pip3 install -e 'git+https://github.com/ckan/ckanext-geoview.git@master#egg=ckanext-geoview'

###Hierarchy###
RUN pip3 install -e "git+https://github.com/ckan/ckanext-hierarchy.git#egg=ckanext-hierarchy"

### Pages ###
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages

### DCAT ###
RUN  pip3 install -e git+https://github.com/ckan/ckanext-dcat.git@v2.4.2#egg=ckanext-dcat && \
    pip3 install -r https://raw.githubusercontent.com/ckan/ckanext-dcat/v2.4.2/requirements.txt

##################################
### LIBRERIAS DE DATOS GOBAR #####
##################################

### Spatial Widget AR ###
RUN pip3 install -e 'git+https://github.com/datosgobar/ckanext-spatial-widget-ar.git@development#egg=ckanext-spatial-widget-ar'

### GobAr theme ###
RUN pip3 install -e 'git+https://github.com/datosgobar/ckanext-gobar-theme.git@development#egg=ckanext-gobar_theme'

### Harvester ###
#RUN pip3 install -e 'git+https://github.com/datosgobar/ckanext-gobar-harvest.git@development#egg=ckanext-gobar-harvest' && \
#    pip3 install -r ${APP_DIR}/src/ckanext-gobar-harvest/pip-requirements.txt
# will also require gather_consumer and fetch_consumer processes running (please see https://github.com/ckan/ckanext-harvest)

### Scheming ###
#RUN pip3 install -e "git+https://github.com/datosgobar/ckanext-scheming-gobar@development#egg=ckanext-scheming-gobar"

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime

############################
### EJECUCION DE SCRIPTS ###
############################

# Copy custom initialization scripts
COPY --chown=ckan-sys:ckan-sys docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY --chown=ckan-sys:ckan-sys patches ${APP_DIR}/patches

# Copy script to install sources
COPY --chown=ckan:ckan-sys setup/install_src.sh.override ${APP_DIR}/install_src.sh

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done


